name: flutter_app_publisher
description: Flutter app publisher
version: 1.3.4
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_app_publisher

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  app_package_publisher: ^0.3.4
  dio: ^5.1.2
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  parse_app_package: ^0.3.4
  qiniu_sdk_base: ^0.5.0
  shell_executor: ^0.1.4
dev_dependencies:
  dependency_validator: ^3.0.0
